Repository Hannah-Sten/TeXiFy-IDEA, pull requests merged in 2018-11, with the labels that each got.

#732 Add option to disable the out directory
  src/nl/rubensten/texifyidea/run/BibtexCommandLineState.kt
  src/nl/rubensten/texifyidea/run/LatexCompiler.java
  src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
  src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
Labels: enhancement

#730 Added option to disable auto bracketing in sub and superscript mode.
  src/nl/rubensten/texifyidea/editor/UpDownAutoBracket.kt
  src/nl/rubensten/texifyidea/settings/TexifyConfigurable.kt
  src/nl/rubensten/texifyidea/settings/TexifySettings.kt
Labels: enhancement

#731 Added autocomplete for \documentclass.
  src/nl/rubensten/texifyidea/TexifyIcons.java
  src/nl/rubensten/texifyidea/completion/LatexDocumentclassProvider.kt
  src/nl/rubensten/texifyidea/completion/TexifyCompletionContributor.kt
  src/nl/rubensten/texifyidea/index/IndexCommandsUtilBase.kt
  src/nl/rubensten/texifyidea/run/LatexCompiler.java
  src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
  src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
  src/nl/rubensten/texifyidea/util/Files.kt
  src/nl/rubensten/texifyidea/util/Magic.kt
  src/nl/rubensten/texifyidea/util/Platforms.kt
  src/nl/rubensten/texifyidea/util/Projects.kt
Labels: enhancement

#751 Added support for natbib citation commands
  src/nl/rubensten/texifyidea/inspections/latex/LatexCollapseCiteInspection.kt
  src/nl/rubensten/texifyidea/inspections/latex/LatexUnresolvedReferenceInspection.kt
  src/nl/rubensten/texifyidea/lang/LatexNoMathCommand.kt
  src/nl/rubensten/texifyidea/lang/Package.kt
  src/nl/rubensten/texifyidea/reference/LatexLabelReference.java
  src/nl/rubensten/texifyidea/util/Magic.kt
Labels: enhancement

#752 Documentation: add sumatrapdf instructions to installation instructions
  README.md
Labels: enhancement

#755 Add latexmk support
  src/nl/rubensten/texifyidea/run/LatexCompiler.java
  src/nl/rubensten/texifyidea/run/LatexCompiler.kt
  src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
  src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
  src/nl/rubensten/texifyidea/run/compiler/BibtexCompiler.kt
  src/nl/rubensten/texifyidea/util/OperatingSystem.kt
  src/nl/rubensten/texifyidea/util/Platforms.kt
  src/nl/rubensten/texifyidea/util/Strings.kt
Labels: enhancement

#756 Update linux instructions
  README.md
Labels: enhancement

#720 Add Biber support
  src/nl/rubensten/texifyidea/completion/handlers/LatexCommandPackageIncludeHandler.kt
  src/nl/rubensten/texifyidea/documentation/LatexDocumentationProvider.kt
  src/nl/rubensten/texifyidea/index/IndexUtilBase.kt
  src/nl/rubensten/texifyidea/inspections/latex/LatexAvoidEqnarrayInspection.kt
  src/nl/rubensten/texifyidea/inspections/latex/LatexEllipsisInspection.kt
  src/nl/rubensten/texifyidea/inspections/latex/LatexExtremeInequalityInspection.kt
  src/nl/rubensten/texifyidea/inspections/latex/LatexGatherEquationsInspection.kt
  src/nl/rubensten/texifyidea/inspections/latex/LatexMathOperatorEscapeInspection.java
  src/nl/rubensten/texifyidea/inspections/latex/LatexMissingImportInspection.kt
  src/nl/rubensten/texifyidea/lang/DefaultEnvironment.kt
  src/nl/rubensten/texifyidea/lang/LatexNoMathCommand.kt
  src/nl/rubensten/texifyidea/lang/Package.kt
  src/nl/rubensten/texifyidea/run/BibtexRunConfiguration.kt
  src/nl/rubensten/texifyidea/run/LatexCommandLineState.kt
  src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
  src/nl/rubensten/texifyidea/run/LatexRunConfigurationProducer.kt
  src/nl/rubensten/texifyidea/run/compiler/BiberCompiler.kt
  src/nl/rubensten/texifyidea/run/compiler/BibliographyCompiler.kt
  src/nl/rubensten/texifyidea/run/compiler/BibtexCompiler.kt
  src/nl/rubensten/texifyidea/util/FileSet.kt
  src/nl/rubensten/texifyidea/util/Psi.kt
Labels: enhancement

#761 Fixes #760 compatibility with future versions
  build.gradle
Labels: bug, high-priority

#766 Use bibtex executablename in bibtex run config
  src/nl/rubensten/texifyidea/run/compiler/BibtexCompiler.kt
Labels: bug, high-priority

#781 Convert TexifyProjectComponent to StartupActivity
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/components/TexifyProjectComponent.kt
  src/nl/rubensten/texifyidea/startup/TexifyStartupActivity.kt
Labels: enhancement

#784 Replace OperatingSystem usages with com.intellij.openapi.util.SystemInfo
  src/nl/rubensten/texifyidea/run/LatexCompiler.kt
  src/nl/rubensten/texifyidea/run/LatexRunConfiguration.java
  src/nl/rubensten/texifyidea/run/LatexSettingsEditor.java
  src/nl/rubensten/texifyidea/run/compiler/BibtexCompiler.kt
  src/nl/rubensten/texifyidea/ui/PreviewFormUpdater.kt
  src/nl/rubensten/texifyidea/util/OperatingSystem.kt
Labels: enhancement

#785 Change Gradle task in 'building from source' instructions from zip to buildPlugin
  README.md
Labels: bug

#787 Made LatexNavigationGutter configurable
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/gutter/LatexCompileGutter.kt
  src/nl/rubensten/texifyidea/gutter/LatexLineMarkerProvider.kt
  src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
Labels: enhancement

#783 Reconfigured LaTeX menu actions.
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/action/group/AnalysisActionGroup.kt
  src/nl/rubensten/texifyidea/action/group/LatexAnalyzeMenuGroup.kt
  src/nl/rubensten/texifyidea/action/group/LatexEditMenuGroup.kt
  src/nl/rubensten/texifyidea/action/group/LatexToolsMenuGroup.kt
Labels: enhancement

#786 Syntax highlighting for labels and font style
  src/nl/rubensten/texifyidea/highlighting/LatexAnnotator.kt
  src/nl/rubensten/texifyidea/highlighting/LatexColorSettingsPage.kt
  src/nl/rubensten/texifyidea/highlighting/LatexSyntaxHighlighter.java
  src/nl/rubensten/texifyidea/util/Magic.kt
Labels: enhancement
