Repository Hannah-Sten/TeXiFy-IDEA, pull requests merged in 2019-01, with the labels that each got.

#789 Added "goto symbol" support for labels, bibitems, cmd. def., and env. def.
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/navigation/GotoCommandDefinitionSymbolContributor.kt
  src/nl/rubensten/texifyidea/navigation/GotoEnvironmentDefinitionSymbolContributor.kt
  src/nl/rubensten/texifyidea/navigation/GotoLabelSymbolContributor.kt
  src/nl/rubensten/texifyidea/navigation/NavigationItemUtil.kt
  src/nl/rubensten/texifyidea/navigation/TexifyGotoSymbolBase.kt
  src/nl/rubensten/texifyidea/structure/latex/LatexLabelPresentation.kt
  src/nl/rubensten/texifyidea/util/Commands.kt
  src/nl/rubensten/texifyidea/util/Environments.kt
  src/nl/rubensten/texifyidea/util/Labels.kt
  src/nl/rubensten/texifyidea/util/Magic.kt
  src/nl/rubensten/texifyidea/util/Psi.kt
Labels: enhancement

#798 Update faq with corrupt cache fix
  README.md
Labels: documentation

#801 Fraction live template
  resources/liveTemplates/hidden/Math.xml
  src/nl/rubensten/texifyidea/completion/handlers/LatexMathInsertHandler.java
  src/nl/rubensten/texifyidea/completion/handlers/LatexMathInsertHandler.kt
  src/nl/rubensten/texifyidea/templates/LatexLiveTemplateProvider.kt
Labels: enhancement

#802 Manual checks for package inclusions both in commands and environments
  src/nl/rubensten/texifyidea/inspections/latex/LatexMissingImportInspection.kt
Labels: enhancement

#804 Add bibtex inspections for addbibresource
  src/nl/rubensten/texifyidea/completion/handlers/FileNameInsertionHandler.kt
  src/nl/rubensten/texifyidea/inspections/bibtex/BibtexDuplicateBibliographyInspection.kt
  src/nl/rubensten/texifyidea/structure/latex/LatexStructureViewElement.kt
  src/nl/rubensten/texifyidea/util/Magic.kt
Labels: bug
