Repository Hannah-Sten/TeXiFy-IDEA, pull requests merged in 2019-11, with the labels that each got.

#983 Make sentenceEnd not trigger on trailing space.
  src/nl/hannahsten/texifyidea/inspections/latex/LatexSpaceAfterAbbreviationInspection.kt
  src/nl/hannahsten/texifyidea/util/Magic.kt
Labels: bug

#1073 Open pdf viewer when no extra compiles are needed
  src/nl/hannahsten/texifyidea/run/latex/LatexCommandLineState.kt
Labels: alpha, bug

#1074 Default to pdflatex when no compiler is chosen
  resources/META-INF/plugin.xml
  src/nl/hannahsten/texifyidea/run/latex/ui/LatexSettingsEditor.kt
Labels: crash-report

#1090 LatexDuplicatedLabelInspection findLabels crash
  src/nl/hannahsten/texifyidea/inspections/latex/LatexDuplicateLabelInspection.kt
  src/nl/hannahsten/texifyidea/util/Labels.kt
Labels: crash-report

#1116 Update to 2019.3 and update dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build
