Repository Hannah-Sten/TeXiFy-IDEA, pull requests merged in 2019-02, with the labels that each got.

#814 Configure inverse search correctly when no 32-bit Java is available
  README.md
  src/nl/rubensten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
Labels: bug

#817 Move items from Analyze menu to Code menu in non-IntelliJ IDEs
  .github/CODEOWNERS
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/action/AnalyzeMenuRegistration.kt
Labels: crash-report

#818 Fix label not shown in structure view
  src/nl/rubensten/texifyidea/structure/latex/LatexStructureViewElement.kt
Labels: bug

#800 Fixed issue in #795
  src/nl/rubensten/texifyidea/folding/LatexSectionFoldingBuilder.kt
Labels: enhancement

#822 Add Gradle task to upload to the alpha channel
  README.md
  build.gradle
  gradle/credentials.properties
Labels: enhancement

#829 Added 'Goto symbol' support for section markers.
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/navigation/GotoSectionDefinitionSymbolContributor.kt
  src/nl/rubensten/texifyidea/navigation/NavigationItemUtil.kt
  src/nl/rubensten/texifyidea/util/Labels.kt
  src/nl/rubensten/texifyidea/util/PsiCommands.kt
Labels: enhancement

#828 Added method separators for sections.
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/insight/LatexLineMarkerProvider.kt
Labels: enhancement

#831 Fixed several wrong triggers of Grouped Sub sup Script inspection.
  src/nl/rubensten/texifyidea/inspections/latex/LatexGroupedSubSupScriptInspection.kt
  test/nl/rubensten/texifyidea/inspections/latex/LatexGroupedSubSupScriptInspectionTest.kt
  test/nl/rubensten/texifyidea/inspections/latex/TexifyRegexInspectionTestBase.kt
Labels: bug

#830 Improved crash report submitting process.
  src/nl/rubensten/texifyidea/blame/LatexErrorReportSubmitter.java
  src/nl/rubensten/texifyidea/blame/LatexErrorReportSubmitter.kt
Labels: bug, crash-report, enhancement

#832 Add xelatex compiler
  src/nl/rubensten/texifyidea/run/LatexCompiler.kt
Labels: enhancement

#816 Removes wrong file not found marker for Images
  src/nl/rubensten/texifyidea/inspections/latex/LatexFileNotFoundInspection.kt
  src/nl/rubensten/texifyidea/util/Files.kt
Labels: bug

#823 Preserve blank lines in new file for long sections
  src/nl/rubensten/texifyidea/util/Strings.kt
Labels: bug
