Repository Hannah-Sten/TeXiFy-IDEA, pull requests merged in 2019-04, with the labels that each got.

#866 \citet commands (and variants) without non-breaking space being flagged
  src/nl/rubensten/texifyidea/inspections/latex/LatexNonBreakingSpaceInspection.kt
Labels: bug

#864 Added \LoadClass support and added autocompletion of custom packages
  resources/nl/rubensten/texifyidea/packages/package.list
  src/nl/rubensten/texifyidea/completion/LatexPackageNameProvider.kt
  src/nl/rubensten/texifyidea/completion/TexifyCompletionContributor.kt
  src/nl/rubensten/texifyidea/gutter/LatexNavigationGutter.java
  src/nl/rubensten/texifyidea/lang/LatexRegularCommand.kt
  src/nl/rubensten/texifyidea/util/Magic.kt
Labels: enhancement

#863 Fixed crash #861: LatexCiteBeforePeriod quickfix at the end of a file.
  src/nl/rubensten/texifyidea/inspections/latex/LatexCiteBeforePeriodInspection.kt
Labels: bug, crash-report

#862 Word count only analyses LaTeX files
  src/nl/rubensten/texifyidea/action/analysis/WordCountAction.kt
Labels: bug

#854 Doc: Add macro procedure
  README.md
  doc/macro.png
Labels: documentation

#841 Gradle: better way of providing credentials to publishPlugin
  .github/CODEOWNERS
  build.gradle
  gradle.properties
  gradle/credentials.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: build, enhancement

#846 Update Gradle dependencies and IJ to 2019.1
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build, enhancement

#844 Skip negative text ranges when adding folding sections
  src/nl/rubensten/texifyidea/folding/LatexSectionFoldingBuilder.kt
Labels: bug, crash-report

#870 Added icon for TikZ files.
  resources/nl/rubensten/texifyidea/icons/tikz-file.svg
  src/nl/rubensten/texifyidea/TexifyIcons.java
  src/nl/rubensten/texifyidea/action/NewLatexFileAction.java
  src/nl/rubensten/texifyidea/file/TikzFileType.kt
  src/nl/rubensten/texifyidea/templates/LatexTemplatesFactory.kt
  src/nl/rubensten/texifyidea/util/Magic.kt
Labels: enhancement

#851 Register LaTeX project creation in non-IntelliJ IDEs
  README.md
  build.gradle
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/modules/DefaultFileCreator.kt
  src/nl/rubensten/texifyidea/modules/LatexModuleBuilder.kt
  src/nl/rubensten/texifyidea/modules/LatexProjectGenerator.kt
  src/nl/rubensten/texifyidea/modules/LatexProjectGeneratorPeer.kt
Labels: build, enhancement

#836 Toggle math environments
  resources/META-INF/plugin.xml
  resources/intentionDescriptions/LatexMathToggle/description.html
  src/nl/rubensten/texifyidea/action/ShowEquationPreview.kt
  src/nl/rubensten/texifyidea/editor/MathEnvironmentEditor.kt
  src/nl/rubensten/texifyidea/editor/MultiLineMathContentToOneLine.kt
  src/nl/rubensten/texifyidea/intentions/LatexMathToggle.kt
  src/nl/rubensten/texifyidea/ui/MathEnvironmentDialog.kt
  src/nl/rubensten/texifyidea/util/Magic.kt
  src/nl/rubensten/texifyidea/util/Psi.kt
  test/nl/rubensten/texifyidea/editor/OneLinerTest.kt
Labels: enhancement

#871 Fixed bad SumatraPDF menu formatting
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/action/group/SumatraActionGroup.java
  src/nl/rubensten/texifyidea/action/group/SumatraActionGroup.kt
  src/nl/rubensten/texifyidea/action/sumatra/ConfigureInverseSearchAction.kt
  src/nl/rubensten/texifyidea/action/sumatra/ForwardSearchAction.kt
Labels: bug

#837 Tikz Preview
  README.md
  resources/META-INF/plugin.xml
  src/nl/rubensten/texifyidea/action/ShowEquationPreview.kt
  src/nl/rubensten/texifyidea/action/preview/PreviewAction.kt
  src/nl/rubensten/texifyidea/action/preview/ShowEquationPreview.kt
  src/nl/rubensten/texifyidea/action/preview/ShowTikzPreview.kt
  src/nl/rubensten/texifyidea/ui/PreviewForm.form
  src/nl/rubensten/texifyidea/ui/PreviewFormUpdater.kt
  src/nl/rubensten/texifyidea/util/Packages.kt
Labels: enhancement

#879 Added the \newtheorem command to the auto complete
  src/nl/rubensten/texifyidea/util/Magic.kt
Labels: enhancement
